# Generated by Django 4.2.2 on 2025-05-07 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_suscripcion', models.CharField(max_length=250, verbose_name='Nombre Suscripción')),
                ('valor_suscripcion', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Suscripción')),
                ('fecha_alta', models.DateField(auto_now_add=True, verbose_name='Fecha Alta Suscripción')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha Vencimiento')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado Suscripción')),
                ('nota', models.TextField(blank=True, null=True, verbose_name='Nota')),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-id'],
            },
        ),
    ]
