# Generated by Django 4.2.2 on 2025-05-07 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suscripcion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscripcion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='tipo_cobro_suscrip',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('anual', 'Anual')], default='mensual', max_length=10, verbose_name='Tipo de Suscripción'),
        ),
        migrations.CreateModel(
            name='SuscripcionPorUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('fecha_cobro_suscrip', models.DateField(verbose_name='Fecha Cobro Suscripción')),
                ('fecha_fin_suscrip', models.DateField(verbose_name='Fin de Suscripción')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('nota', models.TextField(verbose_name='Nota')),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asociados', to='suscripcion.suscripcion', verbose_name='Suscripción')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion_asociada', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Suscripción por Usuario',
                'verbose_name_plural': 'Suscripciones por Usuario',
            },
        ),
    ]
