# Generated by Django 4.2.2 on 2025-05-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripcion', '0002_remove_suscripcion_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='limite_clientes',
            field=models.IntegerField(default=0, verbose_name='Límite de Clientes'),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='limite_empleados',
            field=models.IntegerField(default=0, verbose_name='Límite de Empleados'),
        ),
    ]
