# Generated by Django 5.1 on 2025-05-08 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripcion', '0003_suscripcion_limite_clientes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoSuscriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Pago')),
                ('metodo_pago', models.CharField(blank=True, choices=[('tarjeta', 'Tarjeta de Crédito/Débito'), ('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria')], max_length=50, null=True, verbose_name='Método de Pago')),
                ('estado_pago', models.CharField(choices=[('completado', 'Completado'), ('pendiente', 'Pendiente'), ('fallido', 'Fallido')], default='completado', max_length=20, verbose_name='Estado del Pago')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Nota')),
                ('suscripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suscripcion.suscripcion', verbose_name='Suscripcion Asociada')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_suscrip_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asociado')),
            ],
            options={
                'verbose_name': 'Pago Suscripción',
                'verbose_name_plural': 'Pagos Suscripciones',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
