# Generated by Django 5.1 on 2025-05-11 05:20

import uuid
from django.db import migrations, models


def generar_referencias(apps, schema_editor):
    Pago = apps.get_model('suscripcion', 'PagoSuscriptor')
    for pago in Pago.objects.all():
        pago.referencia = str(uuid.uuid4()).split('-')[0].upper()
        pago.save()

class Migration(migrations.Migration):

    dependencies = [
        ('suscripcion', '0005_alter_suscripcionporusuario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosuscriptor',
            name='referencia',
            field=models.CharField(max_length=100, default='', editable=False),
            preserve_default=False,
        ),
        migrations.RunPython(generar_referencias),
        migrations.AlterField(
            model_name='pagosuscriptor',
            name='referencia',
            field=models.CharField(max_length=100, unique=True, editable=False),
        ),
    ]