# Generated by Django 5.1 on 2025-05-11 05:47
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('suscripcion', '0006_pagosuscriptor_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosuscriptor',
            name='token',
            field=models.CharField(
                max_length=64,
                unique=True,
                null=True,  # Importante para poder aplicarla sin errores
                editable=False,
                verbose_name='Token de acceso seguro'
            ),
        ),
    ]
