# Generated by Django 5.1 on 2025-05-11 06:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripcion', '0008_auto_20250511_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagosuscriptor',
            name='referencia',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True, verbose_name='Referencia de Pago'),
        ),
        migrations.AlterField(
            model_name='pagosuscriptor',
            name='token',
            field=models.CharField(editable=False, max_length=64, unique=True, verbose_name='Token de acceso seguro'),
        ),
    ]
