# Generated by Django 5.1 on 2025-05-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='cliente',
            new_name='usuario_padre',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('superusuario', 'Superusuario'), ('usuario', 'Usuario'), ('subusuario', 'Subusuario')], default='usuario', max_length=20),
        ),
    ]
