# Generated by Django 5.1 on 2025-05-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_cliente_usuario_usuario_padre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_area',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Código de Área'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia'),
        ),
    ]
