# Generated by Django 5.1 on 2025-04-29 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
        ('promociones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promociones.promo', verbose_name='Promocion Asociada'),
        ),
    ]
