# Generated by Django 5.1 on 2025-05-17 01:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_pagos_referencia_pagos_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='referencia',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True, verbose_name='Referencia de Pago'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='token',
            field=models.CharField(default='3767df2bb63c4c51ab625060d11f6f84', editable=False, max_length=64, unique=True, verbose_name='Token de acceso seguro'),
        ),
    ]
