# Generated by Django 5.1 on 2025-05-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0006_alter_pagos_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='referencia',
            field=models.CharField(editable=False, max_length=100, unique=True, verbose_name='Referencia de Pago'),
        ),
    ]
