# Generated by Django 5.1 on 2025-05-17 01:38

from django.db import migrations


import uuid

def asignar_referencia_y_token(apps, schema_editor):
    Pago = apps.get_model('pagos', 'Pagos')  # ajusta al nombre de tu app y modelo
    for pago in Pago.objects.filter(referencia__isnull=True):
        pago.referencia = str(uuid.uuid4())
        pago.token = uuid.uuid4().hex
        pago.save()

class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0008_alter_pagos_referencia_alter_pagos_token'),
    ]

    operations = [
        migrations.RunPython(asignar_referencia_y_token),
    ]
