# Generated by Django 5.1 on 2025-05-17 01:49

from django.db import migrations

import uuid

def generar_referencias_unicas(apps, schema_editor):
    Pagos = apps.get_model('pagos', 'Pagos')
    for pago in Pagos.objects.filter(referencia__isnull=True):
        pago.referencia = str(uuid.uuid4())
        pago.token = uuid.uuid4().hex
        pago.save()

class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0011_alter_pagos_referencia_alter_pagos_token'),
    ]

    operations = [
        migrations.RunPython(generar_referencias_unicas),
    ]
