# Generated by Django 5.1 on 2025-05-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0014_alter_pagos_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='token',
            field=models.CharField(editable=False, max_length=64, unique=True, verbose_name='Token de acceso seguro'),
        ),
    ]
