# Generated by Django 5.1 on 2025-05-13 21:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_initial'),
        ('visitas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitaServis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Visita')),
                ('nombre_promocion', models.CharField(max_length=250, verbose_name='Nombre Promoción')),
                ('b_disponible', models.IntegerField(default=0, verbose_name='Bidones Disponibles')),
                ('b_entregado', models.IntegerField(default=0, verbose_name='Bidones Entregados')),
                ('b_retirado', models.IntegerField(default=0, verbose_name='Bidondes retirados')),
                ('b_en_poder_clte', models.IntegerField(default=0, verbose_name='Bidones en poder del cliente')),
                ('referencia', models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True, verbose_name='Referencia de Visita')),
                ('token', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Token de acceso seguro')),
                ('nota', models.TextField(blank=True, null=True, verbose_name='Nota u Observación')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.cliente', verbose_name='Cliente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visita_servis_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asociado')),
            ],
            options={
                'verbose_name': 'Visita Servicio',
                'verbose_name_plural': 'Visitas Servicios',
                'ordering': ['-fecha_visita'],
            },
        ),
    ]
