# Generated by Django 5.1 on 2025-05-15 22:42

from django.db import migrations
import uuid


def generar_token_y_referencia(apps, schema_editor):
    Visita = apps.get_model('visitas', 'Visita')
    for visita in Visita.objects.filter(token__isnull=True):
        visita.token = uuid.uuid4().hex
        visita.referencia = str(uuid.uuid4())
        visita.save()

class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0003_visita_referencia_visita_token'),
    ]

    operations = [
        migrations.RunPython(generar_token_y_referencia),
    ]
