# Generated by Django 5.1 on 2025-05-15 22:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0004_auto_20250515_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='referencia',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True, verbose_name='Referencia de Visita'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='token',
            field=models.CharField(editable=False, max_length=64, unique=True, verbose_name='Token de acceso seguro'),
        ),
    ]
