# Generated by Django 5.1 on 2025-04-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=150, verbose_name='Dirección')),
                ('fecha_alta', models.DateField(auto_now_add=True, verbose_name='Fecha de Alta')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PromoPorCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_promo', models.DateTimeField(auto_now_add=True, verbose_name='Inicio de Promo')),
                ('fin_promo', models.DateField(verbose_name='Fin de Promo')),
                ('fecha_pago_promo', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago Promo')),
                ('bidones_disponibles', models.IntegerField(verbose_name='Bidones Disponibles')),
                ('entrega_bidones', models.IntegerField(default=0, verbose_name='Entrega de Bidones')),
                ('retorno_bidones', models.IntegerField(default=0, verbose_name='Retorno de Bidones')),
                ('bidones_acumulados', models.IntegerField(default=0, verbose_name='Bidones Acumulados')),
                ('codigo_dispenser', models.CharField(max_length=20, verbose_name='Código Dispenser')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('nota', models.TextField(verbose_name='Nota')),
            ],
            options={
                'verbose_name': 'Promoción por Cliente',
                'verbose_name_plural': 'Promociones por Cliente',
                'ordering': ['-id'],
            },
        ),
    ]
