# Generated by Django 5.1 on 2025-04-29 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('promociones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asociado'),
        ),
        migrations.AddField(
            model_name='promoporcliente',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promociones', to='cliente.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='promoporcliente',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promociones.promo', verbose_name='Promoción'),
        ),
        migrations.AddField(
            model_name='promoporcliente',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promos_clientes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asociado'),
        ),
    ]
